[package]
name = "cswire"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ff = "0.5.0"
ark-crypto-primitives = { version = "0.5.0", features = ["sponge", "r1cs"] }
itertools = "0.14.0"

[dev-dependencies]
ark-bn254 = "0.5.0"
ark-std = "0.5.0"
